spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://spring-boot-mysql:3306/docker
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1

