spring:
  jpa:
    hibernate:
      ddl-auto: validate
  database: mysql
  datasource:
    url: jdbc:mysql://wonwoo.ml:18802/docker
    username: root
    password: dheh123
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1

