spring:
  jpa:
    hibernate:
      ddl-auto: validate
  database: mysql
  datasource:
    url: jdbc:mysql://mysql:3306/docker
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1

